version: '3'
services:
    postgresdb:
        container_name: postgres_container
        image: postgres:latest
        environment:
          POSTGRES_USER: ${POSTGRES_USER:-postgres}
          POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-docker}
          PGDATA: /data/postgres
        volumes:
          - postgres_data:/var/lib/postgres
          - ./dbscripts/postgres:/docker-entrypoint-initdb.d
        ports:
          - "5432:5432"
        networks:
          - postgres
        restart: unless-stopped
networks:
  postgres:
    driver: bridge

volumes:
    postgres_data:
